set_property SRC_FILE_INFO {cfile:/home/ferry/dev/DE2/chisel-lab/lab8/sevenseg-cnt.xdc rfile:../../../../../../sevenseg-cnt.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports *]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clock]
